/* Copyright (c) 2017-2019, The Linux Foundation. All rights reserved.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 2 and
* only version 2 as published by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*/

/*
 * this file was generated by NunniFSMGen
 */


#ifndef altek_state_H
#define altek_state_H

#include "altek_statefsm.h"

#ifdef __cplusplus
extern "C"
{
#endif		/* __cplusplus */


int state_open(void *o);
int error_sequence(void *o);
int redundant_sequence(void *o);
int state_enter_hwpt(void *o);
int state_coldboot(void *o);
int state_close(void *o);
int state_leave_hwpt(void *o);
int state_scenario_chg(void *o);
int state_strm_on_off(void *o);
int state_enter_cp(void *o);
int state_set_qp(void *o);
int state_stop(void *o);
int state_leave_cp(void *o);
int state_leave_cp_standy(void *o);


#ifdef __cplusplus
}
#endif		/* __cplusplus */


#endif
